# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-Account-AutoDiscovery
version:      0.01
version_from: lib/Catalyst/Plugin/Account/AutoDiscovery.pm
installdirs:  site
requires:
    Catalyst:                      5.30

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
